config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :brands
  get 'vacancies/index'

  get 'vacancies/show'

  get 'vacacies/index'

  get 'vacacies/show'

  resources :vacancies
  resources :discounts
  resources :line_items
  resources :carts
  resources :pets do
    resources :stuffs
  end

   root 'pets#index'

end

app/models/stuff.rb
class Stuff < ActiveRecord::Base
  belongs_to :pet
  belongs_to :discount
  belongs_to :brand
  belongs_to :user
   
  mount_uploader :picture, PictureUploader
  
  has_many :carts, through: :line_items
  has_many :line_items
  
  has_many :weights
  accepts_nested_attributes_for :weights, reject_if: :all_blank, allow_destroy: true

  serialize :color, Array

  enum group: { toys: 0, leads: 1, foods: 2, filler: 3 }

  scope :only_discount, -> { where.not(sale: 0) }

  validates :name, :pet_id, presence: true
  # validates :price, numericality: { greater_than: 0}
end

app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  before_action :set_stuff, only: [:show, :edit, :update, :destroy]
  before_action :set_pet

  # GET /stuffs
  # GET /stuffs.json
  def index
    @stuffs = @pet.stuffs.send(params[:group]).sort_by { |st| st.name }
    @pets = Pet.all
  end

  # GET /stuffs/1
  # GET /stuffs/1.json
  def show
    @pets = Pet.all
  end

  # GET /stuffs/new
  def new
    @stuff = Stuff.new
  end

  # GET /stuffs/1/edit
  def edit
  end

  # POST /stuffs
  # POST /stuffs.json
  def create
    @stuff = Stuff.new(stuff_params)

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to pet_stuff_path(@pet, @stuff), notice: 'Stuff was successfully created.' }
        format.json { render :show, status: :created, location: @stuff }
        puts params[:stuff]
      else
        format.html { render :new }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuffs/1
  # PATCH/PUT /stuffs/1.json
  def update
    respond_to do |format|
      if @stuff.update(stuff_params)
        format.html { redirect_to pet_stuff_path(@pet, @stuff), notice: 'Stuff was successfully updated.' }
        format.json { render :show, status: :ok, location: @stuff }
      else
        format.html { render :edit }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1
  # DELETE /stuffs/1.json
  def destroy
    @stuff.destroy
    respond_to do |format|
      format.html { redirect_to pet_stuffs_path(@pet), notice: 'Stuff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuff
      @stuff = Stuff.find(params[:id])
    end

    def set_pet
      @pet = Pet.find(params[:pet_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stuff_params
      params.require(:stuff).permit(:pet_id, :name, :size, :description, :brand_id, :discount_id, :group, :price, 
                                    :picture, :sale, :annotation, color: [], weights_attributes: [:id, :stuff_id, :price, :size, :_destroy])
    end


end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/views/stuffs/_form.html.haml
= form_for ([@pet, @stuff]) do |f|
  - if @stuff.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stuff.errors.count, "error")} prohibited this stuff from being saved:"
      %ul
        - @stuff.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :pet_id
    = f.select :pet_id, Pet.all.map {|p| [p.name, p.id]}
  
  .field
    .input-group
      = f.label t(:name)
      = f.text_field :name
 
  #weights
    = f.fields_for :weights do |weight|
      = render "shared/weight_fields", f: weight
    .links
      = link_to_add_association 'add weight', f, :weights, :partial => 'shared/weight_fields'
  
  .field
    .input_group
      = f.label t(:description)
      = f.text_area :description, :class => "form-control"
  .field
    - ['red', 'blue', 'black', 'brown', 'grey', 'pink', 'green', 'yellow', 'violet'].each do |a|
      = f.label "color_#{a}", a
      = check_box_tag "stuff[color][]", a, @stuff.color.include?(a), id: "stuff_color_#{a}"
    

  .field
    = f.label :brand_id
    = f.select :brand_id, Brand.all.map {|br| [br.name, br.id]}
  .field
    = f.label :discount_id 
    = f.select :discount_id, Discount.all.map {|d| [d.name, d.id]}, { include_blank: true }
  .field
    = f.label :sale
    = f.number_field :sale
  .actions
    = f.submit 'Save', class: "btn btn-default"

app/views/stuffs/edit.html.haml
%h1 Редактирование товара

= render 'form'

= link_to 'Show', pet_stuff_path(@pet, @stuff)
\|
= link_to 'Back', pet_stuffs_path(@pet)

app/views/stuffs/index.html.haml
.container
  .row
    =render "shared/left_column"

    .col-lg-9
      - @stuffs.each_slice(3) do |slice|
        .row
          - slice.each do |stuff|
            .col-lg-4{style: 'padding-bottom: 15px;'}
              - if stuff.sale?
                = render "shared/sale_stuff", stuff: stuff
              -else  
                = render "shared/stuff", stuff: stuff
        / %td= link_to 'Show', pet_stuff_path(@pet, @stuff)
        / %td= link_to 'Edit', edit_pet_stuff_path(@pet, @stuff)
        / %td= link_to 'Destroy', pet_stuff_path(@pet), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/stuffs/new.html.haml
%h4 Создание товара

= render 'form'

= link_to 'Back', pet_stuffs_path

app/views/stuffs/show.html.haml
.container
  .row
    = render "shared/left_column"
    .col-lg-9        
      .bread_crumbs
        = link_to t(@stuff.pet.name), pet_path(@pet)
        = t(@stuff.group)
        = @stuff.name
      .stuff_show_block
        .col-lg-5
          .stuff_show_picture
            = image_tag @stuff.picture, size: "300x300"
        .col-lg-7
          .stuff_show_name
            = @stuff.name
          .stuff_show_annotation  
            = @stuff.annotation
          .brand 
            Брэнд:
            = @stuff.brand.name
            = image_tag @stuff.brand.picture.brand_stuff
          .brand  
            Страна:
            = @stuff.brand.country
          .brand
            Размер:
            = "#{@stuff.size} см"     
       
          .stuff_show_description
            = @stuff.description

          = form_for LineItem.new, url: carts_path  do |f|
            - if @stuff.weights.present?                
              - @stuff.weights.each do |a|
                .wp
                  .row
                    .col-lg-3
                      .weight
                        = "#{a.size} кг"
                    .col-lg-5
                      - if @stuff.sale > 0
                        .stuff_price_discount
                          = "#{a.price} руб"  
                        .stuff_price_weight
                          = "#{(100 - @stuff.sale) * a.price / 100} руб."
                      - else 
                        .stuff_price
                          = "#{a.price} руб"      
                    .col-lg-4
                      .field
                        = f.hidden_field :stuff_id, value: @stuff.id
                        = f.hidden_field :weight_id, value: a.id  
                        = f.submit 'купить', class: 'btn btn-danger'    
          
            - else
              .row.colors
                - if @stuff.color.present?
                  - @stuff.color.each_slice(4) do |slice|
                    - slice.each do |color|
                      .color-item
                        = image_tag "#{color}.jpg", size: '25x25'
                        = f.label color
                        = f.radio_button :color, color
              .row
                .col-lg-6{style: 'padding-top: 8px;'}
                  - if @stuff.sale > 0
                    .stuff_price_discount
                      = "#{@stuff.price} руб."
                    .stuff_price_weight
                      = "#{(100 - @stuff.sale) * @stuff.price / 100} руб."        
                  - else
                    .stuff_price
                      = "#{@stuff.price} руб."        
                        
                .col-lg-3
                  .field
                    = f.hidden_field :stuff_id, value: @stuff.id
                  .actions
                    = f.submit 'купить', class: 'btn btn-danger' 
                      
              
      .row     
        .col-lg-12
          .brand_description
            = image_tag @stuff.brand.picture.brand, style: "float: left;"
            = @stuff.brand.description
 
      - if can? :update, @stuff    
        = link_to 'Edit', edit_pet_stuff_path(@pet, @stuff)
      \|
      = link_to 'Back', pet_stuffs_path(@pet)