config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :brands
  get 'vacancies/index'

  get 'vacancies/show'

  get 'vacacies/index'

  get 'vacacies/show'

  resources :vacancies
  resources :discounts
  resources :line_items
  resources :carts
  resources :pets do
    resources :stuffs
  end

   root 'pets#index'

end

app/models/pet.rb
class Pet < ActiveRecord::Base

  has_many :stuffs
  mount_uploader :picture, PictureUploader

  validates :name, presence: true

  
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
    @discounts = Discount.all
    @stuffs = Stuff.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @pets = Pet.all
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :size, :groups, :picture)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.haml
= form_for @pet do |f|
  - if @pet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pet.errors.count, "error")} prohibited this pet from being saved:"
      %ul
        - @pet.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.file_field :picture  
  .actions
    = f.submit 'Save'

app/views/pets/edit.html.haml
%h1 Editing pet

= render 'form'

= link_to 'Show', @pet
\|
= link_to 'Back', pets_path

app/views/pets/index.html.haml
/ .pets_main
/   .row
/     - @pets.each do |pet|
/       .col-lg-2
/         .pets_main_one
/           = link_to (image_tag pet.picture.pet), pet
/         .pet_up_name
/           = link_to t(pet.name), pet

.discount_main
  #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
    .carousel-inner
      .item.active
        = image_tag('1.jpg', class: "center-block")
      - @discounts.each do |discount|
        .item
          = link_to( image_tag(discount.picture.discount_show, class: "center-block") , discount)

    %a.left.carousel-control{href: "#carousel-example-generic", role: "button", "data-slide" => "prev"}
      %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
      %span.sr-only
        Previous

    %a.right.carousel-control{href: "#carousel-example-generic", role: "button", "data-slide" => "next"}
      %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
      %span.sr-only
        Next

.container
  .row
    .col-lg-3
      - @pets.each do |pet|
        .pet_name
          = link_to (image_tag pet.picture.pet, size: '60x60'), pet
          = link_to t(pet.name), pet_path(pet)
          %br
        - if pet == @pet
          - pet.stuffs.map(&:group).uniq.each do |group|
            .stuff_left
              = link_to t(group), pet_stuffs_path(@pet, {group: group})
            %br      
    .col-lg-9

      .discount_main
      - @stuffs.only_discount.group_by(&:pet).each do |pet, group|
        .best_offer_pet
          = t(pet.name)
        
        - group.first(6).each_slice(3).with_index do |slice, index|
          .row
            - slice.each do |stuff|
              .col-lg-4
                = render "shared/sale_stuff", stuff: stuff       

                        


                   
                 

        

/ .discount_main

/   .best_offer
/     - @stuffs.only_discount.group_by(&:pet).each do |pet, group|
/       .best_offer_pet
/         = t(pet.name)
/       - group.each_slice(4) do |slice|
/         .row
/           - slice.each do |item|
/             .item
/               .col-lg-3
/                 .stuff_block
/                   .stuff_name
/                     = link_to item.name, [item.pet, item]
/                   .brand
/                     = item.brand.downcase
/                   .weight  
/                     = "#{item.weight} кг"
/                   = link_to (image_tag item.picture.stuff_ind), [item.pet, item]
/                   .stuff_price_discount
/                     = "#{item.price} руб"
/                   .stuff_price
/                     = "#{item.price - (item.price/100 * item.sale)} руб"

/                   = form_for LineItem.new, url: carts_path  do |f|

/                     .field
/                       = f.hidden_field :stuff_id, value: item.id

/                       = f.number_field :quantity
/                       = button_to 'add'



/ %td= link_to 'Show', pet
/ %td= link_to 'Edit', edit_pet_path(pet)
/ %td= link_to 'Destroy', pet, :method => :delete, :data => { :confirm => 'Are you sure?' }



/ = link_to 'New Pet', new_pet_path

app/views/pets/new.html.haml
%h1 New pet

= render 'form'

= link_to 'Back', pets_path

app/views/pets/show.html.haml
.container
  .row
    .col-lg-3
      - @pets.each do |pet|
        .pet_name
          = link_to (image_tag pet.picture.pet, size: '60x60'), pet
          = link_to t(pet.name), pet_path(pet)
          %br
        - if pet == @pet
          - pet.stuffs.map(&:group).uniq.each do |group|
            .stuff_left
              = link_to t(group), pet_stuffs_path(@pet, {group: group})
            %br

    .col-lg-9
      .best_offer
        Лучшие предложения от "Главное - хвост!"
      %br
      - (@pet.stuffs.only_discount).each_slice(3) do |slice|
        .row
          - slice.each do |stuff|
            .col-lg-4
              =render "shared/sale_stuff", stuff: stuff