config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :brands
  get 'vacancies/index'

  get 'vacancies/show'

  get 'vacacies/index'

  get 'vacacies/show'

  resources :vacancies
  resources :discounts
  resources :line_items
  resources :carts
  resources :pets do
    resources :stuffs
  end

   root 'pets#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  
  has_many :line_items, dependent: :destroy
  has_many :stuffs, through: :line_items

  accepts_nested_attributes_for :line_items

 #  def add_stuff(stuff_id)
 #     current_stuff = line_items.find_by(stuff_id: stuff_id)
 #     if current_stuff
 #         current_stuff.quantity += 1
 #     else
 #         current_stuff = line_items.build(stuff_id: stuff_id)
 #     end
 #     current_stuff
 # end

 #  def add_stuff2(stuff_id)
 #    if cart.stuffs.include?(stuff_id)
 #      positions.where(stuff_id: stuff.id).first.increment!(:quantity) 
 #    else
 #      positions.create(item: i, quantity: 1) 
 #    end
 #  end  

  def price_weight
    line_items.with_weight.map {|li| (li.weight.price - (li.weight.price/100 * li.stuff.sale)) * li.quantity }.sum
  end
  
  def price_weight_not
    line_items.map { |li| (li.stuff.price - (li.stuff.price/100 * li.stuff.sale)) * li.quantity }.sum
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    # @cart = Cart.new(cart_params)
    @cart = Cart.last || Cart.create
    @line_item = LineItem.create(
                      cart: @cart,
                      weight_id: params[:line_item][:weight_id], 
                      stuff_id: params[:line_item][:stuff_id],
                      color: params[:line_item][:color]
                    )
    flash[:error] = @line_item.errors.full_messages

    redirect_to :back
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|

      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(line_items_attributes: [:id, :quantity])
    end   
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
.container
  = form_for @cart do |f|
    = f.fields_for :line_items do |li|
      .row
        .col-lg-2
          = link_to (image_tag li.object.stuff.picture.stuff_cart), pet_stuff_path(li.object.stuff.pet, li.object.stuff)
        .col-lg-3   
          = link_to li.object.stuff.name
          %br
          = li.object.stuff.brand.name 
          %br
          - if li.object.color.present?
            = li.object.color
            = image_tag "#{li.object.color}.jpg", size: '15x15' 
          -if li.object.weight_id.present?
            - @weight = Weight.find(li.object.weight_id)
            = "#{@weight.size} кг" 
        .col-lg-1  
          = li.text_field :quantity, style: "width: 50px", value: li.object.quantity
        .col-lg-1
          = "#{li.object.stuff.sale} %"
        .col-lg-2
          -if li.object.weight_id.present?
            = @weight.price - (@weight.price/100 * li.object.stuff.sale)
          - else
            = li.object.stuff.price - (li.object.stuff.price/100 * li.object.stuff.sale)
        .col-lg-2
          -if li.object.weight_id.present?
            = (@weight.price - (@weight.price/100 * li.object.stuff.sale)) * li.object.quantity
          - else
            = (li.object.stuff.price - (li.object.stuff.price/100 * li.object.stuff.sale)) * li.object.quantity 
             
        .col-lg-1
          = link_to (image_tag 'delete3.png', size: '20x20'), li.object, :method => :delete, :data => { :confirm => 'Are you sure?' }   

    =  @cart.price_weight_not + @cart.price_weight
    
    .actions
      = f.submit 'Рассчитать'




  

  
           
 