config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :brands
  get 'vacancies/index'

  get 'vacancies/show'

  get 'vacacies/index'

  get 'vacacies/show'

  resources :vacancies
  resources :discounts
  resources :line_items
  resources :carts
  resources :pets do
    resources :stuffs
  end

   root 'pets#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :stuffs
  mount_uploader :picture, BrandUploader
  
  validates :name, :description, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  
  has_many :line_items, dependent: :destroy
  has_many :stuffs, through: :line_items

  accepts_nested_attributes_for :line_items

 #  def add_stuff(stuff_id)
 #     current_stuff = line_items.find_by(stuff_id: stuff_id)
 #     if current_stuff
 #         current_stuff.quantity += 1
 #     else
 #         current_stuff = line_items.build(stuff_id: stuff_id)
 #     end
 #     current_stuff
 # end

 #  def add_stuff2(stuff_id)
 #    if cart.stuffs.include?(stuff_id)
 #      positions.where(stuff_id: stuff.id).first.increment!(:quantity) 
 #    else
 #      positions.create(item: i, quantity: 1) 
 #    end
 #  end  

  def price_weight
    line_items.with_weight.map {|li| (li.weight.price - (li.weight.price/100 * li.stuff.sale)) * li.quantity }.sum
  end
  
  def price_weight_not
    line_items.map { |li| (li.stuff.price - (li.stuff.price/100 * li.stuff.sale)) * li.quantity }.sum
  end

end

app/models/discount.rb
class Discount < ActiveRecord::Base
  has_many :stuffs

  mount_uploader :picture, DiscountUploader

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :stuff
  belongs_to :cart
  belongs_to :weight

  scope :with_weight, -> {where.not( weight_id: nil)}

  validates :stuff_id, :cart_id, presence: true
  validates :color, presence: true, if: :color_present?
 
  def color_present?
    self.stuff.color.present?
  end 
end

app/models/pet.rb
class Pet < ActiveRecord::Base

  has_many :stuffs
  mount_uploader :picture, PictureUploader

  validates :name, presence: true

  
end

app/models/stuff.rb
class Stuff < ActiveRecord::Base
  belongs_to :pet
  belongs_to :discount
  belongs_to :brand
  belongs_to :user
   
  mount_uploader :picture, PictureUploader
  
  has_many :carts, through: :line_items
  has_many :line_items
  
  has_many :weights
  accepts_nested_attributes_for :weights, reject_if: :all_blank, allow_destroy: true

  serialize :color, Array

  enum group: { toys: 0, leads: 1, foods: 2, filler: 3 }

  scope :only_discount, -> { where.not(sale: 0) }

  validates :name, :pet_id, presence: true
  # validates :price, numericality: { greater_than: 0}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stuffs      
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :stuff

  validates :size, :stuff_id, presence: true
  validates :price, numericality: { greater_than: 0}
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Petshop"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag :cocoon
    <link href='https://fonts.googleapis.com/css?family=Forum|Neucha|Rubik&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="/app/assets/images/fav.ico" type="image/x-icon">
  %body
    .container
      .header_0
        .row
          .user
            .col-lg-6
              .email
                - if user_signed_in?
                  = current_user.email
                  |
                  = link_to 'выйти', destroy_user_session_path, :method => :delete 
                - else
                  = link_to 'войдите', new_user_session_path
                  = '//'
                  = link_to 'зарегистрируйтесь', new_user_registration_path 
            .col-lg-6
              .cart_field
                - if @cart.present? && @cart.line_items.present?
                  = image_tag 'cart.png', size: '40x40'
                  .item_count
                    = link_to @cart.line_items.count, cart_path(@cart)
                - else
                  = image_tag 'cart.png', height: '40', width: '40'
                  ='0 товаров'
      .header_1
        .row
          .col-lg-8
            .company_name
              Главное - хвост !
              .subcompany
                интернет-магазин товаров для домашних животных
          .col-lg-4
            .phone
              = image_tag 'phone.png', height: '30', width: '45'

              (890) 789-654-312


        .logo_icon
          .row
            .col-lg-2
              = link_to (image_tag 'Home.png', size: '50x50'), pets_path
              .logo_title
                = link_to 'главная', pets_path
            .col-lg-2
              = image_tag 'email6.png', height: '50', width: '50'
              .logo_title
                напишите нам письмо
            .col-lg-2
              = image_tag 'deliv3.png', height: '55', width: '55'
              .logo_title
                оплата и доставка
            .col-lg-2
              = link_to (image_tag 'case.png', size: '50x50'), brands_path
              .logo_title
                = link_to 'бренды', brands_path
            .col-lg-2
              = link_to (image_tag 'work.png',  size: '50x50'), vacancies_path
              .logo_title
                =link_to 'вакансии', vacancies_path
            .col-lg-2
              = link_to (image_tag 'sale.png', size: '50x50'), discounts_path
              .logo_title
                = link_to 'акции', discounts_path





      = bootstrap_flash
      = yield

  %footer
    %p &copy; Company 2015

app/views/shared/_left_column.html.haml
.col-lg-3
  - @pets.each do |pet|
    .pet_name
      = link_to (image_tag pet.picture.pet, size: '60x60'), pet
      = link_to t(pet.name), pet_path(pet)
      %br
    - if pet == @pet
      - pet.stuffs.map(&:group).uniq.each do |group|
        .stuff_left
          = link_to t(group), pet_stuffs_path(@pet, {group: group})
        %br

app/views/shared/_sale_stuff.html.haml
.stuff_block
  .stuff_name
    .row
      .col-lg-12
        = link_to "#{stuff.brand.name} #{stuff.name} #{stuff.annotation}", [stuff.pet, stuff]
    .row
      .col-lg-12
        = link_to (image_tag stuff.picture.stuff_ind), [stuff.pet, stuff] 
      .col-lg-12
        -if stuff.color
          - stuff.color.each_slice(5) do |slice|
            %br
            .row
              - slice.each do |color|
                = image_tag "#{color}.jpg", size: '25x25'    
    
    - if stuff.weights.present?                
      - stuff.weights.each do |a|
        .wp
          .row
            .col-lg-5
              .weight
                = "#{a.size} кг"
            .col-lg-7
              .stuff_price_discount
                = "#{a.price} руб"
              - if stuff.sale > 0
                .stuff_price_weight
                  = "#{(100 - stuff.sale) * a.price / 100} руб."
           
    - else 
      .row
        .col-lg-12{style: 'padding-top: 8px;'}
          .stuff_price_discount
            = "#{stuff.price} руб."
          - if stuff.sale > 0
            .stuff_price_weight
              = "#{(100 - stuff.sale) * stuff.price / 100} руб."  
        
          

app/views/shared/_stuff.html.haml
.stuff_block
  .stuff_name
    .row
      .col-lg-12
        = link_to "#{stuff.brand.name} #{stuff.name} #{stuff.annotation}", [stuff.pet, stuff]
    .row
      .col-lg-12
        = link_to (image_tag stuff.picture.stuff_ind), [stuff.pet, stuff] 
      .col-lg-12
        -if stuff.color
          - stuff.color.each_slice(5) do |slice|
            %br
            .row
              - slice.each do |color|
                = image_tag "#{color}.jpg", size: '25x25'

    
    - if stuff.weights.present?                
      - stuff.weights.each do |a|
        .wp
          .row
            .col-lg-4
              .weight
                = "#{a.size} кг"
            .col-lg-8
              .stuff_price
                = "#{a.price} руб"
            
              
    - else 
      .stuff_price
        .row
          .col-lg-12{style: 'padding-top: 8px;'}
            .stuff_price
              = "#{stuff.price} руб."  
         
  
              

                

app/views/shared/_weight_fields.html.haml
.nested-fields
  .field
    = f.label :kg
    = f.number_field :size
    = f.label :rub
    = f.number_field :price
    = link_to_remove_association "remove weight", f    